### ISSUE TITLE
[cands] Image not showing in ds9

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/MOP#349]
Peculiar interaction with ds9 and the image display. 
A candidate is loaded by the python part: the source locations are drawn correctly with the aperture. The image stamps are present and loaded, but not shown. If ds9 is manually forced to realign the image, via Zoom -> Centre Image, the image will appear and be shown to be completely correct: however, the aperture circle vanishes. Hitting tab with the python tool selected momentarily shows the next image in the correct place, then it vanishes leaving only a white background and the correctly positioned aperture circle. Successive tab presses with the python tool selected repeat the cycle of white backgrounds with correctly positioned aperture circles. 
However, successive tab presses with the ds9 window selected after recentering one of the images cycles between the image stamps with them all visible and in the correct place. But no aperture circles visible.

**Comment by ijiraq** [comment]
I had this happen to me also. I think this is caused by an error in the code that computes the ‘cutout’ X/Y location of the mark. I’ll need to dig around and find that. IF / WHEN this happens again please try and figure out the FIELD/CCD/ X/ Y location of the source so that I can track this down.  Perhaps related to chip 36/37 flip issue.

JJ

**Comment by mtbannister** [comment]
It was either 15AP+1+0_s25.measure3.reals.astrom or 15AP+1+0_s21.measure3.reals.astrom. Probably the first.

**Comment by mtbannister** [comment]
This seems to have subsequently gone away with continuing x/y improvements.
